// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Commercially.iOS
{
	public partial class StatusPickerView : UIPickerView
	{
		Status[] Statuses = { Status.New, Status.Assigned, Status.Completed, Status.Cancelled };

		public StatusPickerView(IntPtr handle) : base(handle) { }
		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.DequeueReusableCell("cell", indexPath);
			cell.TextLabel.Text = Statuses[indexPath.Row].ToString();
			return cell;
		}

		public nint NumberOfSections(UITableView tableView)
		{
			return 1;
		}

		public override nint RowsInSection(UITableView tableview, nint section)
		{
			return Statuses.Length;
		}
	}
}
